services:
  nuxeo:
    image: nuxeo-angular-sample:2023.0.0-SNAPSHOT
    ports:
      - "8080:8080"
      - "8787:8787"
    environment:
      NUXEO_DEV: "true"
      NUXEO_CLID: ${NUXEO_CLID}
      NUXEO_PACKAGES: ${NUXEO_PACKAGES}
    volumes:
      - ./conf.d:/etc/nuxeo/conf.d
      - data:/var/lib/nuxeo
volumes:
  data: {}
